(() => {
  const MODAL='rage-client-editor';
  const list=()=>{try{return Array.isArray(clientes)?clientes:[]}catch(_){return[]}};
  const client=id=>list().find(c=>Number(c.id)===Number(id));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>{const x=Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:0};
  const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const dateES=v=>{try{return v&&typeof formatearFechaES==='function'?formatearFechaES(v):(v||'Sin fecha')}catch(_){return v||'Sin fecha'}};
  const save=()=>{if(typeof guardarDatos==='function')guardarDatos()};
  function close(){document.getElementById(MODAL)?.remove()}
  function refresh(id){save();if(typeof verificarPagosPendientes==='function')verificarPagosPendientes();if(typeof verificarEstadoBonos==='function')verificarEstadoBonos();if(typeof actualizarResumen==='function')actualizarResumen();if(typeof renderClientes==='function')renderClientes();if(typeof renderPagos==='function')renderPagos();close();if(typeof verFichaCliente==='function')verFichaCliente(id)}
  function modal({tag='CLIENTE',title,desc='',body,saveText='Guardar cambios',onSave}){close();const w=document.createElement('div');w.id=MODAL;w.innerHTML=`<div class="rage-editor-backdrop"></div><section class="rage-editor-modal"><header class="rage-editor-head"><div><span>${esc(tag)}</span><h3>${esc(title)}</h3>${desc?`<p>${esc(desc)}</p>`:''}</div><button class="rage-editor-close" type="button">×</button></header><div class="rage-editor-body">${body}</div><footer class="rage-editor-foot"><button class="rage-editor-cancel" type="button">Cancelar</button><button class="rage-editor-save" type="button">${esc(saveText)}</button></footer></section>`;document.body.appendChild(w);w.querySelector('.rage-editor-backdrop').onclick=close;w.querySelector('.rage-editor-close').onclick=close;w.querySelector('.rage-editor-cancel').onclick=close;w.querySelector('.rage-editor-save').onclick=onSave}
  function archiveInvoice(c,p,reason){if(!p.facturaNumero)return;c.facturasAnuladas=Array.isArray(c.facturasAnuladas)?c.facturasAnuladas:[];c.facturasAnuladas.push({numero:p.facturaNumero,fechaFactura:p.facturaFecha||p.fecha||'',anuladaEn:new Date().toISOString(),motivo:reason,pagoId:p.id});delete p.facturaNumero;delete p.facturaFecha}
  function snapshotBono(c,p){if(!c||!p)return;if(p.bonoTotal==null)p.bonoTotal=c.bonoTotal;if(p.bonoDuracion==null)p.bonoDuracion=c.bonoDuracion;if(p.bonoModalidad==null)p.bonoModalidad=c.bonoModalidad}
  window.editarClienteRage=id=>{const c=client(id);if(!c)return;modal({title:'Editar datos del cliente',desc:'Teléfono y email pueden dejarse vacíos y completarse posteriormente.',body:`<label class="rage-editor-field full"><span>Nombre completo *</span><input id="ecName" type="text" value="${esc(c.nombre)}"></label><label class="rage-editor-field"><span>Teléfono</span><input id="ecPhone" type="tel" inputmode="tel" value="${esc(c.telefono)}"></label><label class="rage-editor-field"><span>Email</span><input id="ecEmail" type="text" inputmode="email" autocomplete="email" autocapitalize="none" spellcheck="false" value="${esc(c.email)}"></label><label class="rage-editor-field"><span>Fecha de alta</span><input id="ecDate" type="date" value="${esc(c.fechaAlta)}"></label><label class="rage-editor-field"><span>Estado</span><select id="ecState"><option value="Activo" ${c.estado==='Activo'?'selected':''}>Activo</option><option value="Inactivo" ${c.estado==='Inactivo'?'selected':''}>Inactivo</option></select></label><label class="rage-editor-field full"><span>Observaciones</span><textarea id="ecNotes">${esc(c.observaciones)}</textarea></label>`,onSave:()=>{const name=document.getElementById('ecName').value.trim();if(!name){alert('El nombre es obligatorio.');return}c.nombre=name;c.telefono=document.getElementById('ecPhone').value.trim();c.email=document.getElementById('ecEmail').value.trim();c.fechaAlta=document.getElementById('ecDate').value;c.estado=document.getElementById('ecState').value;c.observaciones=document.getElementById('ecNotes').value.trim();refresh(c.id)}})};
  window.cambiarBonoRage=id=>{const c=client(id);if(!c)return;modal({tag:'BONO',title:'Cambiar o renovar bono',desc:'Las sesiones ya programadas conservan la duración con la que se crearon.',saveText:'Guardar bono',body:`<label class="rage-editor-field"><span>Sesiones del bono *</span><input id="ebTotal" type="number" min="1" step="1" value="${esc(c.bonoTotal||5)}"></label><label class="rage-editor-field"><span>Sesiones disponibles</span><input id="ebLeft" type="number" min="0" step="1" value="${esc(c.bonoDisponible??c.bonoTotal??0)}"></label><label class="rage-editor-field"><span>Duración por sesión</span><select id="ebDuration"><option value="30" ${String(c.bonoDuracion)==='30'?'selected':''}>30 minutos</option><option value="60" ${String(c.bonoDuracion)==='60'?'selected':''}>60 minutos</option></select></label><label class="rage-editor-field"><span>Modalidad</span><select id="ebMode"><option value="Individual" ${c.bonoModalidad==='Individual'?'selected':''}>Individual</option><option value="Pareja" ${c.bonoModalidad==='Pareja'?'selected':''}>Pareja</option></select></label><label class="rage-editor-field full"><span>Cuota (€)</span><input id="ebFee" type="number" min="0" step="0.01" value="${esc(c.cuota)}"></label><label class="rage-editor-check"><input id="ebFull" type="checkbox"><span><strong>Es un bono nuevo: cargar todas las sesiones</strong><small>Las disponibles se igualarán al total elegido.</small></span></label><p class="rage-editor-note">Para corregir un bono ya empezado, deja la casilla desmarcada e indica manualmente las sesiones disponibles.</p>`,onSave:()=>{const total=Math.trunc(n(document.getElementById('ebTotal').value));const full=document.getElementById('ebFull').checked;let left=Math.trunc(n(document.getElementById('ebLeft').value));if(total<1){alert('El bono debe tener al menos una sesión.');return}if(full)left=total;if(left<0||left>total){alert('Las sesiones disponibles deben estar entre 0 y el total.');return}(c.pagos||[]).forEach(p=>snapshotBono(c,p));c.bonoTotal=total;c.bonoDisponible=left;c.bonoDuracion=document.getElementById('ebDuration').value;c.bonoModalidad=document.getElementById('ebMode').value;c.cuota=document.getElementById('ebFee').value;refresh(c.id)}});const full=document.getElementById('ebFull'),left=document.getElementById('ebLeft'),total=document.getElementById('ebTotal');const sync=()=>{left.disabled=full.checked;if(full.checked)left.value=total.value};full.onchange=sync;total.oninput=()=>{if(full.checked)left.value=total.value}};
  window.editarPagoRage=(cid,pid)=>{const c=client(cid),p=c?.pagos?.find(x=>Number(x.id)===Number(pid));if(!c||!p)return;modal({tag:'PAGO',title:'Editar pago registrado',desc:p.facturaNumero?`Tiene asociada la factura ${p.facturaNumero}.`:'Corrige fecha, importe o concepto.',saveText:'Guardar pago',body:`${p.facturaNumero?`<p class="rage-editor-warning">Si modificas el pago, la factura ${esc(p.facturaNumero)} se archivará como anulada y su número no se reutilizará.</p>`:''}<label class="rage-editor-field"><span>Fecha *</span><input id="epDate" type="date" value="${esc(p.fecha||today())}"></label><label class="rage-editor-field"><span>Importe (€) *</span><input id="epAmount" type="number" min="0" step="0.01" value="${esc(p.importe)}"></label><label class="rage-editor-field full"><span>Concepto *</span><input id="epConcept" type="text" value="${esc(p.concepto||'Cuota / bono mensual')}"></label>`,onSave:()=>{const date=document.getElementById('epDate').value,amount=document.getElementById('epAmount').value,concept=document.getElementById('epConcept').value.trim();if(!date||amount===''||n(amount)<0||!concept){alert('Completa correctamente fecha, importe y concepto.');return}const changed=date!==String(p.fecha||'')||amount!==String(p.importe??'')||concept!==String(p.concepto||'');if(changed&&p.facturaNumero){if(!confirm(`La factura ${p.facturaNumero} quedará archivada como anulada. ¿Continuar?`))return;archiveInvoice(c,p,'Pago modificado')}p.fecha=date;p.importe=amount;p.concepto=concept;refresh(c.id)}})};
  window.borrarPagoRage=(cid,pid)=>{const c=client(cid),i=c?.pagos?.findIndex(x=>Number(x.id)===Number(pid));if(!c||i<0)return;const p=c.pagos[i],msg=p.facturaNumero?`El pago tiene la factura ${p.facturaNumero}. Se archivará como anulada y el número no se reutilizará. ¿Borrar el pago?`:`¿Borrar el pago de ${p.importe||0} € del ${dateES(p.fecha)}?`;if(!confirm(msg))return;if(p.facturaNumero)archiveInvoice(c,p,'Pago eliminado');c.pagos.splice(i,1);refresh(c.id)};
  function actions(id){const bar=document.querySelector('#cliente-detalle-section .cliente-detail-toolbar');if(!bar)return;let a=bar.querySelector('.cliente-detail-actions');if(!a){a=document.createElement('div');a.className='cliente-detail-actions';bar.appendChild(a)}let e=a.querySelector('.rage-edit-client');if(!e){e=document.createElement('button');e.className='rage-edit-client';e.type='button';e.textContent='Editar datos';a.appendChild(e)}e.onclick=()=>editarClienteRage(id);let b=a.querySelector('.rage-edit-bono');if(!b){b=document.createElement('button');b.className='rage-edit-bono';b.type='button';b.textContent='Cambiar / renovar bono';a.appendChild(b)}b.onclick=()=>cambiarBonoRage(id)}
  function payments(id){const c=client(id),f=document.getElementById('clienteFicha');if(!c||!f)return;const card=[...f.querySelectorAll('.ficha-card')].find(x=>x.querySelector('h2')?.textContent.trim().toLowerCase()==='pagos');if(!card)return;const old=card.querySelector('.historial-pagos');if(old)old.style.display='none';let box=card.querySelector('.rage-payments-editor');if(!box){box=document.createElement('div');box.className='rage-payments-editor';card.appendChild(box)}const ps=[...(c.pagos||[])].sort((a,b)=>`${b.fecha||''}-${b.id||0}`.localeCompare(`${a.fecha||''}-${a.id||0}`));box.innerHTML=`<div class="rage-payments-editor-head"><h3>Historial editable</h3><span>${ps.length} pago${ps.length===1?'':'s'}</span></div>${ps.length?ps.map(p=>`<div class="rage-payment-edit-row"><div>${esc(dateES(p.fecha))}</div><div><strong>${esc(p.concepto||'Pago')}</strong><small>${p.facturaNumero?`Factura ${esc(p.facturaNumero)}`:'Sin factura emitida'}</small></div><div class="rage-payment-amount">${esc(String(p.importe??0).replace('.',','))} €</div><div class="rage-payment-buttons"><button class="rage-payment-change" onclick="editarPagoRage(${Number(c.id)},${Number(p.id)})">Editar</button><button class="rage-payment-remove" onclick="borrarPagoRage(${Number(c.id)},${Number(p.id)})">Borrar</button></div></div>`).join(''):'<div class="rage-payment-empty">No hay pagos registrados.</div>'}`}
  function install(id){actions(id);payments(id)}
  const prev=window.verFichaCliente;if(typeof prev==='function')window.verFichaCliente=function(id){const r=prev.apply(this,arguments);requestAnimationFrame(()=>install(id));setTimeout(()=>install(id),40);setTimeout(()=>install(id),120);return r};
  const addPrev=window.agregarCliente;if(typeof addPrev==='function')window.agregarCliente=function(){const name=document.getElementById('clienteNombre')?.value.trim(),phone=document.getElementById('clienteTelefono');const before=list().length;if(name&&phone&&!phone.value.trim())phone.value='PENDIENTE';const r=addPrev.apply(this,arguments);if(list().length>before){const nuevo=list()[list().length-1];if(nuevo.telefono==='PENDIENTE')nuevo.telefono='';(nuevo.pagos||[]).forEach(p=>snapshotBono(nuevo,p));save();if(typeof renderClientes==='function')renderClientes()}return r};
  const payPrev=window.registrarPagoCliente;if(typeof payPrev==='function')window.registrarPagoCliente=function(id){const c=client(id),before=new Set((c?.pagos||[]).map(p=>Number(p.id)));const r=payPrev.apply(this,arguments);const nuevo=(c?.pagos||[]).find(p=>!before.has(Number(p.id)));if(nuevo){snapshotBono(c,nuevo);save()}return r};
  const invoiceOriginal=window.generarFacturaRagePDF;async function invoiceWithSnapshot(id){const c=client(id),p=[...(c?.pagos||[])].sort((a,b)=>String(b.fecha||'').localeCompare(String(a.fecha||'')))[0];if(!c||!p||typeof invoiceOriginal!=='function')return;const old={bonoTotal:c.bonoTotal,bonoDuracion:c.bonoDuracion,bonoModalidad:c.bonoModalidad};try{if(p.bonoTotal!=null)c.bonoTotal=p.bonoTotal;if(p.bonoDuracion!=null)c.bonoDuracion=p.bonoDuracion;if(p.bonoModalidad!=null)c.bonoModalidad=p.bonoModalidad;return await invoiceOriginal(id)}finally{Object.assign(c,old)}}
  const payListPrev=window.renderPagos;if(typeof payListPrev==='function')window.renderPagos=function(){const r=payListPrev.apply(this,arguments);setTimeout(()=>document.querySelectorAll('#pagosLista .cliente-row').forEach(row=>{const ver=row.querySelector('.ver-btn'),btn=row.querySelector('.factura-btn');if(!ver||!btn)return;const m=(ver.getAttribute('onclick')||'').match(/\((\d+)\)/);if(m)btn.onclick=()=>invoiceWithSnapshot(Number(m[1]))}),0);return r};
})();
